DATA_FOLDER = '2024-2025/'
REPORT_FILENAME = 'report.json'
REPORT_PATH = DATA_FOLDER + REPORT_FILENAME
SCHEDULE_FILENAME = 'schedule.json'
SCHEDULE_PATH = DATA_FOLDER + SCHEDULE_FILENAME
TEAMS_FILENAME = 'teamList.json'
TEAMS_PATH = DATA_FOLDER + TEAMS_FILENAME
PLAYERS_FILENAME = 'players.json'
PLAYERS_PATH = DATA_FOLDER + PLAYERS_FILENAME
STANDINGS_PATH = DATA_FOLDER + 'weeklyStandings'
SUMMARY_PATH = DATA_FOLDER + 'weeklySummary'
RECAPS_PATH = DATA_FOLDER + 'weeklyRecaps'
leagueId = 130603
year = 2024
season = "f"
Summary_Read = "https://www.leaguesecretary.com/League/Summary_Read"
Team_List_Read = "https://www.leaguesecretary.com/Team/TeamList_Read"
Player_List_Read = "https://www.leaguesecretary.com/Bowler/BowlerByWeekList_Read"
NINE_PIN_WEEK = 9